#!/usr/bin/php

<?php

$search_pictures = glob("*.png");
include 'cssgenerator/function.php';


if(error_image() == 1 & !isset($argv[1])){
  generate_css();
  merge_image(charge_image());
  
}
elseif($argv[1] == "-s" || regex("--output-style=", $argv[1])){
        if(regex("--output-style=", $argv[1]) && !isset($argv[2])){

           generate_css(recupe_name($argv[1]));
           merge_image(charge_image());

        }
        elseif($argv[1] == "-s" && isset($argv[2]) && !isset($argv[3])){
          generate_css($argv[2]);
          merge_image(charge_image());
        }
        else{
         man();
        }

}
elseif($argv[1] == "-i" || regex("--output-image=", $argv[1])){
  if(regex("--output-image=", $argv[1]) && !isset($argv[2])){

     generate_css();
     merge_image(charge_image(), $argv[1]);

  }
  elseif($argv[1] == "-i" && isset($argv[2]) && !isset($argv[3])){
    generate_css();
    merge_image(charge_image(),$argv[2]);
  }
  else{
    man();
  }

}
elseif($argv[1] =="--help" || $argv[1] == "-h"){
  man();
}



 






?>
